# Generated by Django 3.1.12 on 2025-01-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointment_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
