# Generated by Django 5.1.5 on 2025-01-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
    ]
