# Generated by Django 5.1.5 on 2025-01-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_date_of_birth_patient_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='appointment_reason',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date')},
        ),
    ]
