# Generated by Django 5.0.6 on 2025-02-02 01:33

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_picture', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
    ]
