# Generated by Django 5.0.6 on 2025-02-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctor_cropping_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='drive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
