# Generated by Django 5.0.6 on 2025-02-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_doctor_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('DR', 'DR'), ('DRA', 'DRA')], default='', max_length=5),
        ),
    ]
