# Generated by Django 5.0.6 on 2025-02-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('DR.', 'DR.'), ('DRA.', 'DRA.')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
