# Generated by Django 5.0.6 on 2025-02-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doctor_description_alter_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(default='', max_length=380),
        ),
    ]
