# Generated by Django 5.0.6 on 2025-02-02 13:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_patientparent_remove_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientparent',
            name='contact_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='VE'),
        ),
    ]
