# Generated by Django 5.0.6 on 2025-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_patientparent_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pending'), ('Agendada', 'Scheduled'), ('Cancelada', 'Canceled')], default='Pending', max_length=10),
        ),
    ]
