# Generated by Django 5.0.6 on 2025-02-02 18:18

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='patientparent',
            options={'verbose_name': 'Representante', 'verbose_name_plural': 'Representantes'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de consulta'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Agendada', 'Agendada'), ('Cancelada', 'Cancelada')], default='Pending', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(default='', max_length=380, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('DR.', 'DR.'), ('DRA.', 'DRA.')], default='', max_length=5, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='', max_length=100, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patient_parents', to='users.patientparent', verbose_name='Razón de consulta'),
        ),
        migrations.AlterField(
            model_name='patientparent',
            name='contact_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='VE', verbose_name='Número telefónico de contacto'),
        ),
        migrations.AlterField(
            model_name='patientparent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='patientparent',
            name='id_number',
            field=models.CharField(default='', max_length=30, verbose_name='Cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='patientparent',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre y apellido'),
        ),
    ]
