# Generated by Django 3.1.12 on 2025-01-02 00:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
